// frontend-vue/src/components/PersonForm.vue
<template>
  <div class="field is-horizontal">
    <div class="field-label is-medium">
      <label for="firstName"
             class="label">{{ $t('app.people.form.firstName.label') }}</label>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <input
              id="firstName"
              name="firstName"
              type="text"
              :class="{'input': true, 'is-danger': errors.firstName}"
              v-model="formData.firstName"
              :placeholder="$t('app.people.form.firstName.label')"
          />
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-medium">
      <label for="lastName"
             class="label">{{ $t('app.people.form.lastName.label') }}</label>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <input
              id="lastName"
              name="lastName"
              type="text"
              :class="{'input': true, 'is-danger': errors.lastName}"
              v-model="formData.lastName"
              :placeholder="$t('app.people.form.lastName.label')"
          />
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-medium">
      <label for="email"
             class="label">{{ $t('app.people.form.email.label') }}</label>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <input
              id="email"
              name="email"
              type="text"
              :class="{'input': true, 'is-danger': errors.email}"
              v-model="formData.email"
              :placeholder="$t('app.people.form.email.label')"
          />
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-medium">
      <label for="status"
             class="label">{{ $t('app.people.form.status.label') }}</label>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <div class="select is-fullwidth">
            <select
                id="status"
                name="status"
                :class="{'input': true, 'is-danger': errors.status}"
                v-model="formData.status">
              <option
                  value="0">{{ $t('app.people.form.status.value.active') }}
              </option>
              <option
                  value="1">{{ $t('app.people.form.status.value.inactive') }}
              </option>
            </select>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <button type="button" class="button is-primary" @click="submitPerson()">
        {{ $t('app.people.form.submit.label') }}
      </button>
    </div>
  </div>
</template>

<script>
import {computed, reactive, toRefs, watch, watchEffect, inject, toRaw} from 'vue';
import {useRouter} from 'vue-router';
import {isValidEmail} from "../utils/validators";
import {PeopleServiceDIKey} from "../utils/constants";

export default {
  props: {
    id: Number
  },
  setup: function (props) {
    const {id} = toRefs(props);
    const peopleService = inject(PeopleServiceDIKey);
    const router = useRouter();

    const formData = reactive({
      firstName: '',
      lastName: '',
      email: '',
      status: 0
    });

    const errors = reactive({
      firstName: null,
      lastName: null,
      email: isValidEmail(formData.email),
      status: null
    });

    const formHasSomeErrors = computed(() => {
      return errors.firstName
          || errors.lastName
          || errors.email
          || errors.status;
    });

    const submitPerson = () => {
      if (formHasSomeErrors.value) {
        console.log('Form has some errors', errors)
        return;
      }

      const person = toRaw(formData);

      console.log('Submitting person', toRaw(formData));
      if (id?.value) {
        // updating person
        peopleService.updatePerson(id.value, person)
            .then(updated => {
              console.log(`Successfully updated person ${id.value}. New data: `, updated);
              router.push('/');
            });
      } else {
        // creating person
        peopleService.createPerson(person)
            .then(created => {
              console.log('Successfully create person with data: ', created);
              router.push('/');
            });
      }
    };

    const updatePersonStateWithData = person => {
      formData.firstName = person.firstName;
      formData.lastName = person.lastName;
      formData.email = person.email;
      formData.status = person.status;
    };

    watch(
        () => formData.email,
        (curr) => {
          errors.email = isValidEmail(curr);
        }
    )

    if (id?.value) {
      watchEffect(() => {
        peopleService.getPersonById(id.value)
            .then(person => {
              updatePersonStateWithData(person);
            });
      });
    }

    return {formData, personId: id, errors, submitPerson, formHasSomeErrors};
  }
}
</script>

<style lang="scss" scoped>
@import "~bulma";
</style>

// frontend-angular/src/app/people-module/person-form/person-form.component.ts
import {Component, EventEmitter, Input, OnInit, Output} from '@angular/core';
import {FormControl, FormGroup} from '@angular/forms';
import {PeopleService} from '../people.service';
import {Person} from '../models/person';
import {isValidEmail} from '../utils/validators';
import {PersonSubmitted} from '../models/person-submitted';

@Component({
  selector: 'app-person-form',
  templateUrl: './person-form.component.html',
  styleUrls: ['./person-form.component.scss']
})
export class PersonFormComponent implements OnInit {
  @Input('id') personId: string | null = null;
  @Output('personSubmitted') personSubmitted: EventEmitter<PersonSubmitted>
    = new EventEmitter<PersonSubmitted>();
  loaded = false;

  personForm: FormGroup = new FormGroup({
    firstName: new FormControl(''),
    lastName: new FormControl(''),
    email: new FormControl('', [isValidEmail], null),
    status: new FormControl(0)
  });

  constructor(private peopleService: PeopleService) {
  }

  ngOnInit(): void {
    if (this.personId && !Number.isNaN(this.personId)) {
      console.log(`Editing person with id ${this.personId}. Editing mode...`);

      this.peopleService.getPersonById(Number.parseInt(this.personId, 10))
        .then(person => {
          this.updatePersonFormWithData(person);
          this.loaded = true;
        }).catch((e) => {
        console.log(`Failed to fetch person with id ${this.personId}`, e);
        this.loaded = true;
      });

    } else {
      console.log('Person id is undefined - adding mode');
      this.loaded = true;
    }
  }

  private updatePersonFormWithData(person: Person): void {
    this.personForm.controls.firstName.setValue(person.firstName);
    this.personForm.controls.lastName.setValue(person.lastName);
    this.personForm.controls.email.setValue(person.email);
    this.personForm.controls.status.setValue(person.status);
  }

  submitPerson(): void {
    console.log('Submitting person...');
    if (!this.personForm.valid) {
      console.log('Data are not valid');
      return;
    }
    const person = this.personForm.value as Person;
    const personUpdate = !!this.personId;
    if (!personUpdate) {
      this.peopleService.createPerson(person as Person)
        .then(p => {
          console.log(`Create succeeded with id ${p.id}`);
          const event = new PersonSubmitted();
          event.id = p.id;
          event.created = personUpdate;
          this.personSubmitted.emit(event);
        }).catch(e => {
        console.log('Create failed');
      });
    } else {
      // person update
      this.peopleService.updatePerson(Number.parseInt(this.personId as string, 10), person)
        .then(r => {
          if (r == null) {
            console.log('Update failed');
            return;
          }
          const event = new PersonSubmitted();
          event.id = r.id;
          event.created = false;
          this.personSubmitted.emit(event);
        });
    }
  }
}

<div *ngIf="!loaded" class="container loader-wrapper">
  <div class="loader loader-positioned" style="margin: 0 auto"></div>
</div>
<form *ngIf="loaded" [formGroup]="personForm">
  <div class="field is-horizontal">
    <div class="field-label is-medium">
      <label for="firstName" class="label">First name</label>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <input id="firstName"
                 type="text"
                 class="input"
                 placeholder="First name"
                 formControlName="firstName"/>
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-medium">
      <label for="lastName" class="label">Last name</label>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <input id="lastName"
                 type="text"
                 class="input"
                 placeholder="Last name"
                 formControlName="lastName"/>
        </div>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-medium">
      <label for="email" class="label">E-mail</label>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <input id="email"
                 type="text"
                 [ngClass]="{'input': true, 'is-danger': this.personForm?.controls?.email?.errors}"
                 placeholder="E-mail"
                 formControlName="email"/>
        </div>
        <p *ngIf="this.personForm?.controls?.email?.errors" class="help is-danger">E-mail is invalid</p>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-label is-medium">
      <label for="status" class="label">Status</label>
    </div>
    <div class="field-body">
      <div class="field">
        <div class="control">
          <div class="select is-fullwidth">
            <select id="status" formControlName="status">
              <option value="0">Active</option>
              <option value="1">Inactive</option>
            </select>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <button class="button is-primary" (click)="submitPerson()">Submit</button>
    </div>
  </div>
</form>
