// frontend-angular/src/app/app.component.ts
import {Component} from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'frontend';
  notYetImplementedModalActive = false;

  toggleModal(): void {
    this.notYetImplementedModalActive = !this.notYetImplementedModalActive;
  }

}

<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" routerLink="/">
      <h2 class="is-uppercase bold" i18n="app-people-management-limited-label">
        PeopleIndex management limited
      </h2>
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" routerLink="/" i18n="app-home-link-label">
        Home
      </a>

      <a class="navbar-item" routerLink="/people/add" i18="app-add-person-link-label">
        Add person
      </a>

    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <a class="button is-primary" (click)="toggleModal()">
            <strong i18n="app-sign-up-link-label">Sign up</strong>
          </a>
          <a class="button is-light" (click)="toggleModal()">
            <strong i18n="app-log-in-link-label">Log in</strong>
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>

<div class="modal" [ngClass]="{'is-active': notYetImplementedModalActive}">
  <div class="modal-background"></div>
  <div class="modal-content">
    <div class="box" i18n="app-not-implemented-yet">
      Sorry, this is still waiting for implementation.
    </div>
  </div>
  <button class="modal-close is-large" aria-label="close" (click)="toggleModal()"></button>
</div>

<router-outlet></router-outlet>

// frontend-react/src/App.js
import './App.css';
import React from 'react';
import {
    BrowserRouter as Router,
    Switch,
    Route, Link
} from 'react-router-dom';
import GlobalContext from './GlobalContext';
import PeopleIndex from "./views/People/PeopleIndex";
import PeopleAdd from "./views/People/PeopleAdd";
import PeopleEdit from "./views/People/PeopleEdit";
import {PeopleService} from "./views/People/PeopleService";

function App() {
    return (
        <GlobalContext.Provider value={{peopleService: new PeopleService()}}>
            <div>
                <Router>
                    <nav className="navbar" role="navigation" aria-label="main navigation">
                        <div className="navbar-brand">
                            <a className="navbar-item" href="/">
                                <h2 id="logo" className="is-uppercase bold" i18n="app-people-management-limited-label">
                                    PeopleIndex management limited
                                </h2>
                            </a>

                            <a href="#logo" role="button" className="navbar-burger" aria-label="menu"
                               aria-expanded="false"
                               data-target="navbarBasicExample">
                                <span aria-hidden="true"></span>
                                <span aria-hidden="true"></span>
                                <span aria-hidden="true"></span>
                            </a>
                        </div>

                        <div id="navbarBasicExample" className="navbar-menu">
                            <div className="navbar-start">
                                <Link className="navbar-item" to="/">
                                    Home
                                </Link>

                                <Link className="navbar-item" to="/people/add">
                                    Add person
                                </Link>

                            </div>

                            <div className="navbar-end">
                                <div className="navbar-item">
                                    <div className="buttons">
                                        <a href="#logo" className="button is-primary">
                                            <strong>Sign up</strong>
                                        </a>
                                        <a href="#logo" className="button is-light">
                                            <strong>Log in</strong>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </nav>
                    <Switch>
                        <Route path="/people/" exact={true}>
                            <PeopleIndex/>
                        </Route>
                        <Route path="/people/add" exact={true}>
                            <PeopleAdd/>
                        </Route>
                        <Route path="/people/edit/:personId" exact={true} children={<PeopleEdit/>}/>
                        <Route path="/" exact={true}>
                            <PeopleIndex/>
                        </Route>
                        <Route>
                            404 page
                        </Route>
                    </Switch>
                </Router>
            </div>
        </GlobalContext.Provider>
    );
}

export default App;
